##debug日志打印配置
debug: true
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
    org.spring.springboot: debug
  file: classpath:log/server.log
##微信小程序配置
wx:
  miniapp:
    configs:
        - appid: wxca4dc5e4145771f3 #微信小程序的appid
          secret: 8987d118f9cc6503266e606786d38b9b #微信小程序的Secret
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
spring:
##mysql数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
##redis数据源配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait:
        max-idle: 8
        min-idle: 0

    timeout:
##mybatis包扫描配置
mybatis:
  type-aliases-package: org.spring.springboot.domain
  mapper-locations: classpath:mapper/*.xml
##指定端口和地址
server:
  address: 192.168.1.103
  port: 11115

